leader: " "

bindings:

  # Special keys
  - {keys: [<leader>, <space>],
     command: workbench.action.showCommands,
     description: "Run command"}
  - {keys: [<leader>, <tab>],
     command: workbench.action.nextEditor,
     description: "Next editor"}

  # Numbers
  - {keys: [<leader>, 1],
     command: workbench.action.focusFirstEditorGroup,
     description: "Focus first editor group"}
  - {keys: [<leader>, 2],
     command: workbench.action.focusSecondEditorGroup,
     description: "Focus second editor group"}
  - {keys: [<leader>, 3],
     command: workbench.action.focusThirdEditorGroup,
     description: "Focus third editor group"}

  # SPC b - Buffers
  - {keys: [<leader>, b, b],
     command: workbench.action.quickOpen,
     description: "Quick open (show current buffers)"}
  - {keys: [<leader>, b, d],
     command: workbench.action.closeActiveEditor,
     description: "Close active editor"}
  - {keys: [<leader>, b, n],
     command: workbench.action.nextEditor,
     description: "Focus next editor"}
  - {keys: [<leader>, b, p],
     command: workbench.action.previousEditor,
     description: "Focus previous editor"}

  # SPC f - Files
  - {keys: [<leader>, f, f],
     command: workbench.action.files.openFile,
     description: "Open file"}
  - {keys: [<leader>, f, r],
     command: workbench.action.openRecent,
     description: "Open recent (show recent files)"}
  - {keys: [<leader>, f, s],
     command: workbench.action.files.save,
     description: "Save file"}
  - {keys: [<leader>, f, t],
     command: workbench.view.explorer,
     description: "Show explorer view"}

  # SPC g - Source control
  - {keys: [<leader>, g, s],
     command: workbench.view.scm,
     description: "Show source control view"}

  # SPC l - Layouts
  - {keys: [<leader>, l, d],
     command: workbench.action.closeFolder,
     description: "Clode folder"}

  # SPC p - Projects
  - {keys: [<leader>, p, f],
     command: workbench.action.quickOpen,
     description: "Quick open (allow to open any project file)"}
  - {keys: [<leader>, p, l],
     command: workbench.action.files.openFolder,
     description: "Open folder project"}
  - {keys: [<leader>, p, p],
     command: workbench.action.openRecent,
     description: "Open recent (show recent folders)"}

  # SPC q - Quit
  - {keys: [<leader>, q, f],
     command: workbench.action.closeWindow,
     description: "Close window"}
  - {keys: [<leader>, q, q],
     command: workbench.action.closeWindow,
     description: "Close window"}

  # SPC w - Windows
  - {keys: [<leader>, w, w],
     command: workbench.action.focusNextGroup,
     description: "Next editor group"}
  - {keys: [<leader>, w, W],
     command: workbench.action.focusPreviousGroup,
     description: "Previous editor group"}
