# create issue to remember maintainers to renew Azure token

name: Remember Azure token
on:
  schedule:
    # once every 6 months
    - cron:  '0 0 1 */6 *'
jobs:
  remind_token:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/token_reminder_issue.md
